version: '3'

networks:
  nodenet:
    name: nodenet
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data
    driver: local

services:
  app:
    container_name: app
    command: "node index.js"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    tty: true
    build:
      context: ./node
    networks:
      - nodenet
    volumes:
      - ./node:/app
      - /app/node_modules

  nginx:
    container_name: nginx
    tty: true
    restart: always
    build:
      context: ./nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
